id: ID6A8C822
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T01:39:18+00:00'
last_modified: '2022-06-08T02:13:35.433151+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9409
  title: གསུང་འབུམ། འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ། （བླ་བྲང་པར་མ་བསྐྱར་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    85A5:
      image_group_id: I1KG9415
      title: ''
      total_pages: 891
      order: 1
      base_file: 85A5.txt
    4F03:
      image_group_id: I1KG9416
      title: ''
      total_pages: 779
      order: 2
      base_file: 4F03.txt
    4D0C:
      image_group_id: I1KG9417
      title: ''
      total_pages: 903
      order: 3
      base_file: 4D0C.txt
    9BC0:
      image_group_id: I1KG9418
      title: ''
      total_pages: 918
      order: 4
      base_file: 9BC0.txt
    '8778':
      image_group_id: I1KG9419
      title: ''
      total_pages: 850
      order: 5
      base_file: 8778.txt
    3B04:
      image_group_id: I1KG9420
      title: ''
      total_pages: 958
      order: 6
      base_file: 3B04.txt
    '8103':
      image_group_id: I1KG9421
      title: ''
      total_pages: 724
      order: 7
      base_file: 8103.txt
    '6124':
      image_group_id: I1KG9422
      title: ''
      total_pages: 682
      order: 8
      base_file: 6124.txt
    37E7:
      image_group_id: I1KG9423
      title: ''
      total_pages: 898
      order: 9
      base_file: 37E7.txt
    '8529':
      image_group_id: I1KG9424
      title: ''
      total_pages: 1364
      order: 10
      base_file: 8529.txt
    '4149':
      image_group_id: I1KG9425
      title: ''
      total_pages: 702
      order: 11
      base_file: 4149.txt
    8A86:
      image_group_id: I1KG9426
      title: ''
      total_pages: 567
      order: 12
      base_file: 8A86.txt
    B0BB:
      image_group_id: I1KG9427
      title: ''
      total_pages: 883
      order: 13
      base_file: B0BB.txt
    '3634':
      image_group_id: I1KG9428
      title: ''
      total_pages: 1104
      order: 14
      base_file: 3634.txt
    C9FF:
      image_group_id: I1KG9429
      title: ''
      total_pages: 811
      order: 15
      base_file: C9FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
